### ISSUE TITLE
Create seed data for local dev environment

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#7]
_From @leonstafford on June 2, 2017 1:34_

TBC, which user roles and other data is there that needs creating - campaigns, projects, donations, blogs

### Acceptance criteria

 - [x] Reset all local user passwords to `banana` in seed file (run script in fresh sleepbussql container, export and replace seed data with new dump)
 - [x] add volunteers table to seed data to fix other issue re local volunteer signup
 - [x] rm email messages table
 - [x] rm email messages section from zeemoadmin
 - [x] rm zeemoadmin email stuff from codebase
 - [x] rm thank_messages table
 - [x] rm `pages` table

### testing

after removing tables, do site regression test and fix any issues

### Tasks for dev

- [x] `DROP TABLE email_messages;`
- [ ] rm zeemo email settings sections section from `admin_modules`
- [x]  `DROP TABLE thank_messages;`
- [x]  `DROP TABLE pages;` 

### Tasks for prod

- [x] `DROP TABLE email_messages;`
- [ ] rm zeemo email settings section from `admin_modules`
- [x] `DROP TABLE thank_messages;`
- [x]  `DROP TABLE pages;`

**Comment by leonstafford** [comment]
This issue was moved to sleepbusorg/sleepbus.org#4

**Comment by bakersemail** [comment]
I updated the sample seed data to remove all the domain names and found a missing image in the source code as a result: https://www.sleepbus.org/images/ACNC-Registered-Charity-Logo_reverse_300.png

**Comment by leonstafford** [comment]
awesome, thanks!

**Comment by leonstafford** [comment]
note to self - just needs to be merged to dev/prod and said tables and zeemo data manually removed from dbs
